# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.armaRidgeGGMmixture <- function(Y, K, lambda, target, iWeights, nInit, minSuccDiff, minMixProp) {
    .Call(`_porridge_ridgeGGMmixture`, Y, K, lambda, target, iWeights, nInit, minSuccDiff, minMixProp)
}

.armaKcvlGGMmixture <- function(lambda, Y, K, target, iWeights, nInit, minSuccDiff, folds, minMixProp) {
    .Call(`_porridge_kcvlGGMmixture`, lambda, Y, K, target, iWeights, nInit, minSuccDiff, folds, minMixProp)
}

.armaRidgePgen <- function(S, lambda, target, nInit, minSuccDiff) {
    .Call(`_porridge_ridgePgen`, S, lambda, target, nInit, minSuccDiff)
}

.armaKcvlossR <- function(lambda, Y, target, folds, nInit, minSuccDiff) {
    .Call(`_porridge_kcvlossR`, lambda, Y, target, folds, nInit, minSuccDiff)
}

.armaPenaltyPgen_banded <- function(lambda, p, zerosR, zerosC, penalize_diag) {
    .Call(`_porridge_penaltyPgen_banded`, lambda, p, zerosR, zerosC, penalize_diag)
}

.armaPenaltyPgen_groups <- function(lambda, groups, zerosR, zerosC, penalize_diag) {
    .Call(`_porridge_penaltyPgen_groups`, lambda, groups, zerosR, zerosC, penalize_diag)
}

.armaKCVlossR_groups <- function(lambdaGrps, Y, target, folds, groups, zerosR, zerosC, penalize_diag, nInit, minSuccDiff) {
    .Call(`_porridge_kcvlossR_groups`, lambdaGrps, Y, target, folds, groups, zerosR, zerosC, penalize_diag, nInit, minSuccDiff)
}

.armaKCVlossR_banded <- function(lambda, Y, target, folds, zerosR, zerosC, penalize_diag, nInit, minSuccDiff) {
    .Call(`_porridge_kcvlossR_banded`, lambda, Y, target, folds, zerosR, zerosC, penalize_diag, nInit, minSuccDiff)
}

.armaMixTargets <- function(targetList, lambda) {
    .Call(`_porridge_mixTargets`, targetList, lambda)
}

.armaRidgePmultiT <- function(S, lambda, targetList) {
    .Call(`_porridge_armaRidgePmultiT`, S, lambda, targetList)
}

.armaRidgePrepEM <- function(Y, ids, lambdaZ, lambdaE, targetZ, targetE, nInit, minSuccDiff) {
    .Call(`_porridge_ridgePrepEM`, Y, ids, lambdaZ, lambdaE, targetZ, targetE, nInit, minSuccDiff)
}

.armaRidgePrepKcvLL <- function(lambdaZE, Y, ids, targetZ, targetE, nInit, minSuccDiff, folds, CVcrit) {
    .Call(`_porridge_ridgePrepKcvLL`, lambdaZE, Y, ids, targetZ, targetE, nInit, minSuccDiff, folds, CVcrit)
}

.armaRidgePrepEMdiag <- function(Y, ids, lambdaZ, targetZ, nInit, minSuccDiff) {
    .Call(`_porridge_ridgePrepEMdiag`, Y, ids, lambdaZ, targetZ, nInit, minSuccDiff)
}

.armaRidgePrepKcvLLdiag <- function(lambdaZ, Y, ids, targetZ, nInit, minSuccDiff, folds, CVcrit) {
    .Call(`_porridge_ridgePrepKcvLLdiag`, lambdaZ, Y, ids, targetZ, nInit, minSuccDiff, folds, CVcrit)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_porridge_RcppExport_registerCCallable', PACKAGE = 'porridge')
})
